AddonId: MetadataImageOptimizer_17b571ff-6ffe-4bea-ad25-32e52b54f9d3
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2023-12-16
    PackageUrl: https://github.com/UrbanCMC/PlayniteExtensions/releases/download/2023-12-16/MetadataImageOptimizer_1_0.pext
    Changelog:
    - Initial release
    - Support optimization of backgrounds, covers, and icons
    - Extract high quality images from .ico files