AddonId: MetadataImageOptimizer_17b571ff-6ffe-4bea-ad25-32e52b54f9d3
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2023-12-16
    PackageUrl: https://github.com/UrbanCMC/PlayniteExtensions/releases/download/2023-12-16/MetadataImageOptimizer_1_0.pext
    Changelog:
    - Initial release
    - Support optimization of backgrounds, covers, and icons
    - Extract high quality images from .ico files
  - Version: 1.1
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2023-12-18
    PackageUrl: https://github.com/UrbanCMC/PlayniteExtensions/releases/download/2023-12-18/MetadataImageOptimizer_1_1.PlayniteExtensions
    Changelog:
    - Due to a change in file structure, all settings were reset to their default values
    - It is now possible to choose a separate format per image type
    - Added new settings for quality of converted images